version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - pip install hatch
    - hatch run docs:build
    - mkdir -p _readthedocs/html
    - cp -r docs/_build/html/* _readthedocs/html/
