name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen

  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Output of `python -c "import mypackage; print(mypackage.__version__)"`
      placeholder: e.g., 0.1.0

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: e.g., 3.11.5

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - Linux
        - macOS
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Logs, screenshots, config snippets, or any other context
